wandb_version: 1

lr:
  desc: null
  value: 0.01
epoch:
  desc: null
  value: 5
architecture:
  desc: null
  value: VGG13
dataset:
  desc: null
  value: CIFAR-10
_wandb:
  desc: null
  value:
    python_version: 3.9.16
    cli_version: 0.14.2
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1682184049.667597
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 2
      - 16
      - 23
      4: 3.9.16
      5: 0.14.2
      8:
      - 1
      - 3
      - 5
      10:
      - 6
